import EML.Basic
import EML.Term
import Mathlib.Analysis.SpecialFunctions.Log.Basic

/-!
# Sheffer companions of EML — `EDL` and `−EML`

Following Odrzywołek (arXiv:2603.21852, §3.1, lines 273–284), the EML
operator has **two paper-named cousins** that share its single-binary-
operator-plus-one-constant structure (paper equation block
`\label{Sheffers}`):

| Companion  | Definition                          | Constant | Status (paper) |
|------------|-------------------------------------|----------|----------------|
| **EML**    | `eml(x, y) = exp(x) − log(y)`       | `1`      | proved complete for 36 primitives |
| **EDL**    | `edl(x, y) = exp(x) / log(y)`       | `e`      | conjectured complete; empirical via `VerifyBaseSet` |
| **−EML**   | `−eml(y, x) = log(x) − exp(y)`      | `−∞`     | conjectured complete; empirical via `VerifyBaseSet` |

Per-primitive completeness is **proved in the paper only for EML** —
the cousins are confirmed empirically by the Mathematica / Rust
`VerifyBaseSet` procedure, not formally. See
[`Sheffer/PaperSourcing.md`](./Sheffer/PaperSourcing.md) for the line-
level paper citations and SI §1.4 references.

This file provides the **framework scaffolding** for the two cousins:

1. The two binary operations on `ℝ` with explicit domain predicates.
2. The two parallel **term grammars** `EDLTerm` and `NegEMLTerm`,
   each inductively generated by `1`, `var n`, and the companion's
   binary operator.
3. Partial evaluation `eval? : (Nat → ℝ) → <Companion>Term → Option ℝ`
   that returns `none` exactly when a sub-expression falls outside its
   companion's natural domain.
4. The trivial collapse identities (analogous to `eml(x, 1) = exp x`).

## On `−EML`'s constant

The paper's `−EML` requires `−∞` as its distinguished constant:
`negEml(x, −∞) = log(x) − exp(−∞) = log(x) − 0 = log(x)`. In Lean's
finite real partial-eval setting, we cannot literalise `−∞`; closing
`−EML` per-primitive completeness in Lean would need either Mathlib's
`EReal` (extended reals) or a workaround at the witness level. See
**Plan E** in `OPEN_QUESTIONS.md`.

## What's not in this file

The paper's **ternary** operators T₁ and T₂ (SI §1.4, page 8):
```
T₁(x, y, z) = e^(x − y) · ln x / ln z
T₂(x, y, z) = e^(x − y) · ln z / ln x       (with T₂(x, x, x) = 1)
```
These are flagged in the SI as **preliminary unverified candidates**
for a constant-free Sheffer (paper-open question SI §1.5 #3). They are
out of scope for the present formalisation; the earlier scaffolding in
this file that imitated them as binary operators was a misnomer and
has been removed.

Completeness — i.e. simulating each F36 paper primitive inside each
Sheffer grammar — is paper-open. What follows is the **framework
scaffolding** showing the same architectural pattern (grammar / partial
eval / closure lemmas) applies uniformly to both cousins. -/

namespace EML

/-! ## §3.1a — EDL: `edl(x, y) = exp(x) / log(y)` -/

/-- The EDL binary operation. Returns `none` when `log y = 0`,
i.e. when `y = 1` or `y ≤ 0` (the latter via Mathlib's junk-value
convention). -/
noncomputable def edl? (x y : ℝ) : Option ℝ :=
  if Real.log y = 0 then none else some (Real.exp x / Real.log y)

@[simp] lemma edl?_def (x y : ℝ) : edl? x y =
    if Real.log y = 0 then none else some (Real.exp x / Real.log y) := rfl

/-- Abstract syntax of EDL expressions. The grammar includes the paired
constant `e_const` per paper §3.1 (EDL is paired with the constant `e`,
analogous to EML being paired with `1`). -/
inductive EDLTerm
  | one : EDLTerm
  | var : Nat → EDLTerm
  | e_const : EDLTerm
  | edl : EDLTerm → EDLTerm → EDLTerm
  deriving Repr

namespace EDLTerm

/-- Tree-size measure (count of constructors). -/
def size : EDLTerm → Nat
  | one     => 1
  | var _   => 1
  | e_const => 1
  | edl a b => 1 + size a + size b

/-- Partial evaluation under an environment. Returns `none` exactly
when some `edl` sub-expression has `log` of its second argument equal
to zero (junk-value boundary). The if-test is **inlined** rather than
factored through `edl?` so that step-by-step proofs (per Aristotle
chunk 085) compose cleanly via `simp [eval?]`. -/
noncomputable def eval? (env : Nat → ℝ) : EDLTerm → Option ℝ
  | one     => some 1
  | var n   => some (env n)
  | e_const => some (Real.exp 1)
  | edl a b => (eval? env a).bind fun va =>
                 (eval? env b).bind fun vb =>
                   if Real.log vb = 0 then none
                   else some (Real.exp va / Real.log vb)

/-- Every `EDLTerm` has at least one node. -/
lemma size_pos : ∀ t : EDLTerm, 1 ≤ t.size
  | one     => Nat.le_refl 1
  | var _   => Nat.le_refl 1
  | e_const => Nat.le_refl 1
  | edl a b => by show 1 ≤ 1 + a.size + b.size; omega

end EDLTerm

/-! ## §3.1b — −EML: `negEml(x, y) = log(x) − exp(y)`

The "additive cousin" of EML: same `exp/log` ingredients with the roles
swapped — `log` of the *first* argument minus `exp` of the *second*.
The paper's notation `−eml(y, x) = log(x) − exp(y)` (line 280 of
`EML.tex`) flips argument order to make the symmetry with `eml(x, y) =
exp(x) − log(y)` visible; we follow Lean convention and use the
same `(x, y) ↦ log(x) − exp(y)` argument order as our other binaries.

Defined when `0 < x` (so `Real.log x` agrees with the natural
mathematical answer rather than Mathlib's `Real.log 0 = 0` junk value).
The `Real.exp y` term is always positive and so imposes no domain
constraint on `y`. -/

/-- The −EML binary operation. -/
noncomputable def negEml? (x y : ℝ) : Option ℝ :=
  if 0 < x then some (Real.log x - Real.exp y) else none

@[simp] lemma negEml?_def (x y : ℝ) : negEml? x y =
    if 0 < x then some (Real.log x - Real.exp y) else none := rfl

/-- Abstract syntax of `−EML` expressions. The single binary
constructor is named `negEml` to match the operator's paper-level
identity, even though the underlying syntax is in our
finite-real-partial-eval setting (i.e. without the paper's `−∞`
distinguished constant). -/
inductive NegEMLTerm
  | one    : NegEMLTerm
  | var    : Nat → NegEMLTerm
  | negEml : NegEMLTerm → NegEMLTerm → NegEMLTerm
  deriving Repr

namespace NegEMLTerm

/-- Tree-size measure (count of constructors). -/
def size : NegEMLTerm → Nat
  | one        => 1
  | var _      => 1
  | negEml a b => 1 + size a + size b

/-- Partial evaluation under an environment. Returns `none` exactly
when some `negEml` sub-expression has its first argument `≤ 0` (so
`Real.log` would hit the junk-value boundary). -/
noncomputable def eval? (env : Nat → ℝ) : NegEMLTerm → Option ℝ
  | one        => some 1
  | var n      => some (env n)
  | negEml a b => (eval? env a).bind fun va =>
                    (eval? env b).bind fun vb => negEml? va vb

/-- Every `NegEMLTerm` has at least one node. -/
lemma size_pos : ∀ t : NegEMLTerm, 1 ≤ t.size
  | one        => Nat.le_refl 1
  | var _      => Nat.le_refl 1
  | negEml a b => by show 1 ≤ 1 + a.size + b.size; omega

end NegEMLTerm

/-! ## Companion-collapse identities

Each Sheffer companion has a "trivial collapse" identity matching the
paper's `eml(x, 1) = exp x` for EML (i.e. fix one operand to a special
value, recovering a unary primitive). -/

/-- **EDL**: `edl(x, e) = exp(x) / log(e) = exp(x) / 1 = exp(x)`. -/
theorem edl_x_eConst (x : ℝ) :
    edl? x (Real.exp 1) = some (Real.exp x) := by
  simp [edl?_def, Real.log_exp]

/-- **−EML**: `negEml(x, 1) = log(x) − exp(1) = log(x) − e` for `0 < x`.

The paper's natural collapse `negEml(x, −∞) = log(x)` is unavailable in
our finite-real partial-eval; the closest finite-domain analog is the
`y = 1` substitution, which records the additive shift `−e`. The full
collapse to `Real.log x` would require Mathlib's `EReal` extension. -/
theorem negEml_x_one {x : ℝ} (hx : 0 < x) :
    negEml? x 1 = some (Real.log x - Real.exp 1) := by
  simp [negEml?_def, hx]

/-! ## §3.1c — EDL paper-claim witnesses (Plan D progress)

Per-primitive completeness for EDL is paper-open. The witnesses below
are sealed contributions — each provides a literal `EDLTerm` for one
F36 primitive. Five atoms / unaries are sealed so far (Plan D 5/36):

| Primitive | Witness | Provenance |
|-----------|---------|------------|
| `1` | `.one` | trivial |
| `x` | `.var 0` | trivial |
| `e` | `.e_const` | trivial (after grammar extension) |
| `exp x` | `.edl (.var 0) .e_const` | Aristotle chunk 084 |
| `log x` | `.edl .one (.edl (.edl .one (.var 0)) .e_const)` | Aristotle chunk 085 |

The remaining primitives (arithmetic, trig family, hyperbolic) require
witness search; Plan D is paper-open. -/

/-- **D1 / EDL `1`** — Trivial: the `.one` constructor. -/
theorem edl_paper_claim_one :
    ∃ t : EDLTerm, ∀ env : Nat → ℝ, t.eval? env = some 1 :=
  ⟨.one, fun _ => rfl⟩

/-- **D2 / EDL `x`** — Trivial: `.var 0`. -/
theorem edl_paper_claim_var :
    ∃ t : EDLTerm, ∀ env : Nat → ℝ, t.eval? env = some (env 0) :=
  ⟨.var 0, fun _ => rfl⟩

/-- **D3 / EDL `e`** — Trivial after grammar extension: `.e_const`. -/
theorem edl_paper_claim_e_const :
    ∃ t : EDLTerm, ∀ env : Nat → ℝ, t.eval? env = some (Real.exp 1) :=
  ⟨.e_const, fun _ => rfl⟩

/-- **D4 / EDL `exp x`** — `edl(x, e) = exp(x) / log(e) = exp(x) / 1 =
exp(x)`. Witness `edl (var 0) e_const`. (Aristotle chunk 084.) -/
theorem edl_paper_claim_exp :
    ∃ t : EDLTerm, ∀ env : Nat → ℝ, t.eval? env = some (Real.exp (env 0)) := by
  refine ⟨.edl (.var 0) .e_const, fun env => ?_⟩
  simp only [EDLTerm.eval?, Option.bind_some]
  rw [show Real.log (Real.exp 1) = 1 from Real.log_exp 1]
  simp

set_option linter.unusedSimpArgs false in
/-- **D8 / EDL `log x`** — Three-step composition discovered by Aristotle:
- `edl(1, x) = e/log(x)`
- `edl(edl(1, x), e) = exp(e/log(x))/log(e) = exp(e/log(x))`
- `edl(1, edl(edl(1, x), e)) = e/log(exp(e/log(x))) = e/(e/log(x)) = log(x)`

Witness: `edl one (edl (edl one (var 0)) e_const)`. Domain hypothesis:
`0 < env 0` and `env 0 ≠ 1`. (Aristotle chunk 085.) -/
theorem edl_paper_claim_log :
    ∃ t : EDLTerm, ∀ env : Nat → ℝ, 0 < env 0 → env 0 ≠ 1 →
      t.eval? env = some (Real.log (env 0)) := by
  refine ⟨.edl .one (.edl (.edl .one (.var 0)) .e_const), fun env hpos hne1 => ?_⟩
  simp [EDLTerm.eval?]
  split_ifs <;> simp_all +decide [ne_of_gt, Real.exp_pos]
  · grind
  · linarith
  · linarith [Real.exp_pos 1]
  · linarith [Real.exp_pos (Real.exp 1 / Real.log (env 0))]

/-! ## Public summary

This file scaffolds the **two paper-named Sheffer companions** of EML
as proper inductive term grammars with partial-evaluation semantics.
The collapse identities above demonstrate that each grammar can recover
a standard `exp` / `log` family member via a one-step composition.

**Plan D progress:** 5 of 36 EDL paper claims sealed (`one`, `var`,
`e_const`, `exp x`, `log x`). The remaining 31 primitives remain
paper-open; some (e.g. `−1`, `2`, `1/2`) are conjecturally unreachable
from closed EDL terms (Schanuel-conjecture obstruction per Aristotle's
analytical note in `chunks/085_edl_atoms_constants/result.lean`).
Plan E (−EML) per-primitive completeness is also paper-open and not
yet started. -/

end EML
