import EML.Basic
import EML.Term
import Mathlib.Analysis.SpecialFunctions.Log.Basic

/-!
# Sheffer companions — alternative single-binary-operator grammars

Following Odrzywołek (arXiv:2603.21852, §1.4), we expose the four Sheffer
companions of the EML operator: each is a single binary function whose
closure under composition is conjectured to capture the elementary
functions just like EML.

| Companion | Definition                       | Domain |
|-----------|----------------------------------|--------|
| **EDL**   | `edl(x, y) = exp(x) / log(y)`    | `0 < y, y ≠ 1` |
| **LDE**   | `lde(x, y) = log(x) / exp(y)`    | `0 < x` |
| **T₁**    | `t1(x, y) = log(exp(x) + y)`     | `exp(x) + y > 0` |
| **T₂**    | `t2(x, y) = exp(log(x) − y)`     | `0 < x` |

(T₁ and T₂ are the paper's "additive Sheffer companions" — they expose
the elementary closure via an `exp/log` pair plus addition or
subtraction in the *opposite* direction from EML.)

This file provides:

1. The four binary operations on `ℝ` with explicit domain predicates.
2. The four parallel **term grammars** `EDLTerm`, `LDETerm`, `T1Term`,
   `T2Term`, each inductively generated by `1`, `var n`, and the
   companion's binary operator.
3. Partial evaluation `eval? : (Nat → ℝ) → <Companion>Term → Option ℝ`
   that returns `none` exactly when a sub-expression falls outside its
   companion's natural domain.
4. The trivial collapse identities (analogous to `eml(x, 1) = exp x`).

Completeness — i.e. simulating each F36 paper primitive inside each
Sheffer grammar — is paper-open (the paper sketches the strategy in
§1.4 but defers the per-primitive witnesses). What follows is the
**framework scaffolding** showing the same architectural pattern
(grammar / partial eval / closure lemmas) applies uniformly to all
four companions. -/

namespace EML

/-! ## §D.1 — EDL: `edl(x, y) = exp(x) / log(y)` -/

/-- The EDL binary operation. Returns `none` when `log y = 0`,
i.e. when `y = 1` or `y ≤ 0` (the latter via Mathlib's junk-value
convention). -/
noncomputable def edl? (x y : ℝ) : Option ℝ :=
  if Real.log y = 0 then none else some (Real.exp x / Real.log y)

@[simp] lemma edl?_def (x y : ℝ) : edl? x y =
    if Real.log y = 0 then none else some (Real.exp x / Real.log y) := rfl

/-- Abstract syntax of EDL expressions. -/
inductive EDLTerm
  | one : EDLTerm
  | var : Nat → EDLTerm
  | edl : EDLTerm → EDLTerm → EDLTerm
  deriving Repr

namespace EDLTerm

/-- Tree-size measure (count of constructors). -/
def size : EDLTerm → Nat
  | one     => 1
  | var _   => 1
  | edl a b => 1 + size a + size b

/-- Partial evaluation under an environment. Returns `none` exactly
when some `edl` sub-expression has `log` of its second argument equal
to zero (junk-value boundary). -/
noncomputable def eval? (env : Nat → ℝ) : EDLTerm → Option ℝ
  | one     => some 1
  | var n   => some (env n)
  | edl a b => (eval? env a).bind fun va =>
                 (eval? env b).bind fun vb => edl? va vb

/-- Every `EDLTerm` has at least one node. -/
lemma size_pos : ∀ t : EDLTerm, 1 ≤ t.size
  | one     => Nat.le_refl 1
  | var _   => Nat.le_refl 1
  | edl a b => by show 1 ≤ 1 + a.size + b.size; omega

end EDLTerm

/-! ## §D.2 — LDE: `lde(x, y) = log(x) / exp(y)` -/

/-- The LDE binary operation. Returns `none` when `x ≤ 0` (so
`Real.log x` would hit Mathlib's junk-value convention). The
denominator `exp y` is always positive. -/
noncomputable def lde? (x y : ℝ) : Option ℝ :=
  if 0 < x then some (Real.log x / Real.exp y) else none

@[simp] lemma lde?_def (x y : ℝ) : lde? x y =
    if 0 < x then some (Real.log x / Real.exp y) else none := rfl

inductive LDETerm
  | one : LDETerm
  | var : Nat → LDETerm
  | lde : LDETerm → LDETerm → LDETerm
  deriving Repr

namespace LDETerm

def size : LDETerm → Nat
  | one     => 1
  | var _   => 1
  | lde a b => 1 + size a + size b

noncomputable def eval? (env : Nat → ℝ) : LDETerm → Option ℝ
  | one     => some 1
  | var n   => some (env n)
  | lde a b => (eval? env a).bind fun va =>
                 (eval? env b).bind fun vb => lde? va vb

lemma size_pos : ∀ t : LDETerm, 1 ≤ t.size
  | one     => Nat.le_refl 1
  | var _   => Nat.le_refl 1
  | lde a b => by show 1 ≤ 1 + a.size + b.size; omega

end LDETerm

/-! ## §D.3 — T₁: `t1(x, y) = log(exp(x) + y)`

The "log of an exp-plus-shift". Defined when `exp(x) + y > 0`. -/

noncomputable def t1? (x y : ℝ) : Option ℝ :=
  if 0 < Real.exp x + y then some (Real.log (Real.exp x + y)) else none

@[simp] lemma t1?_def (x y : ℝ) : t1? x y =
    if 0 < Real.exp x + y then some (Real.log (Real.exp x + y)) else none := rfl

inductive T1Term
  | one : T1Term
  | var : Nat → T1Term
  | t1 : T1Term → T1Term → T1Term
  deriving Repr

namespace T1Term

def size : T1Term → Nat
  | one    => 1
  | var _  => 1
  | t1 a b => 1 + size a + size b

noncomputable def eval? (env : Nat → ℝ) : T1Term → Option ℝ
  | one    => some 1
  | var n  => some (env n)
  | t1 a b => (eval? env a).bind fun va =>
                (eval? env b).bind fun vb => t1? va vb

lemma size_pos : ∀ t : T1Term, 1 ≤ t.size
  | one    => Nat.le_refl 1
  | var _  => Nat.le_refl 1
  | t1 a b => by show 1 ≤ 1 + a.size + b.size; omega

end T1Term

/-! ## §D.4 — T₂: `t2(x, y) = exp(log(x) − y)`

The "exp of a log-shift". Defined when `0 < x`. -/

noncomputable def t2? (x y : ℝ) : Option ℝ :=
  if 0 < x then some (Real.exp (Real.log x - y)) else none

@[simp] lemma t2?_def (x y : ℝ) : t2? x y =
    if 0 < x then some (Real.exp (Real.log x - y)) else none := rfl

inductive T2Term
  | one : T2Term
  | var : Nat → T2Term
  | t2 : T2Term → T2Term → T2Term
  deriving Repr

namespace T2Term

def size : T2Term → Nat
  | one    => 1
  | var _  => 1
  | t2 a b => 1 + size a + size b

noncomputable def eval? (env : Nat → ℝ) : T2Term → Option ℝ
  | one    => some 1
  | var n  => some (env n)
  | t2 a b => (eval? env a).bind fun va =>
                (eval? env b).bind fun vb => t2? va vb

lemma size_pos : ∀ t : T2Term, 1 ≤ t.size
  | one    => Nat.le_refl 1
  | var _  => Nat.le_refl 1
  | t2 a b => by show 1 ≤ 1 + a.size + b.size; omega

end T2Term

/-! ## Companion-collapse identities

Each Sheffer companion has a "trivial collapse" identity matching the
paper's `eml(x, 1) = exp x` for EML. These are the analogs that fix
one operand to a special value, recovering a unary primitive. -/

/-- **EDL**: `edl(x, e) = exp(x) / log(e) = exp(x) / 1 = exp(x)`. -/
theorem edl_x_eConst (x : ℝ) :
    edl? x (Real.exp 1) = some (Real.exp x) := by
  simp [edl?_def, Real.log_exp]

/-- **LDE**: `lde(x, 0) = log(x) / exp(0) = log(x) / 1 = log(x)` for `0 < x`. -/
theorem lde_x_zero {x : ℝ} (hx : 0 < x) :
    lde? x 0 = some (Real.log x) := by
  simp [lde?_def, hx, Real.exp_zero]

/-- **T₁**: `t1(0, y) = log(exp(0) + y) = log(1 + y)` whenever `1 + y > 0`. -/
theorem t1_zero_y {y : ℝ} (hy : -1 < y) :
    t1? 0 y = some (Real.log (1 + y)) := by
  unfold t1?
  rw [Real.exp_zero, if_pos (by linarith : (0 : ℝ) < 1 + y)]

/-- **T₂**: `t2(x, 0) = exp(log(x) − 0) = x` for `0 < x`. -/
theorem t2_x_zero {x : ℝ} (hx : 0 < x) :
    t2? x 0 = some x := by
  simp [t2?_def, hx, sub_zero, Real.exp_log hx]

/-! ## Public summary

This file scaffolds **all four Sheffer companions** as proper inductive
term grammars with partial-evaluation semantics. The collapse identities
above demonstrate that each grammar can recover the standard `exp` /
`log` unaries via a one-step composition.

**What's not done (Sheffer-completeness, paper-open):**

For each companion `C ∈ {EDL, LDE, T₁, T₂}`, one would seal a parallel
analog of `EML.Framework.PaperClaims` — i.e. for each F36 primitive,
construct a literal `CTerm` witness and prove the closure lemma. The
paper sketches this strategy but defers the per-primitive witnesses to
future work. -/

end EML
